"""creating patients table

Revision ID: 941344f482fb
Revises: ab0d1d1c85c5
Create Date: 2026-01-23 06:49:58.475360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941344f482fb'
down_revision: Union[str, Sequence[str], None] = 'ab0d1d1c85c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients_data', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('patients_data', 'ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients_data', sa.Column('ids', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('patients_data', 'id')
    # ### end Alembic commands ###
