"""added phone num

Revision ID: ca20ad7958c2
Revises: 84871a884a2f
Create Date: 2026-01-23 06:24:03.914404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca20ad7958c2'
down_revision: Union[str, Sequence[str], None] = '84871a884a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients_data', sa.Column('phone', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients_data', 'phone')
    # ### end Alembic commands ###
